# @see https://alacritty.org/config-alacritty.html

[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[general]
import = [
  "$DOTFILES_DIR/submodules/catppuccin/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "MesloLGS NF" 
style = "Regular"

[keyboard]
bindings = [
  { key = '¥', chars= "\\"  },
  # Command + B: 前の単語へ移動 
  { key = "B", mods = "Command", chars = "\u001Bb" }, 
  # Command + F: 次の単語へ移動
  { key = "F", mods = "Command", chars = "\u001Bf" },
]

[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
