# @see https://alacritty.org/config-alacritty.html

[window]
opacity = 1.0
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.normal]
family = "MesloLGS NF" 
style = "Regular"

[keyboard]
bindings = [
  { key = '¥', chars= "\\"  },
  # Command + B: 前の単語へ移動 
  { key = "B", mods = "Command", chars = "\u001Bb" }, 
  # Command + F: 次の単語へ移動
  { key = "F", mods = "Command", chars = "\u001Bf" },
]

