# ----------------------------------------------------
# 1. 基本設定
# ----------------------------------------------------

# プレフィックスキーを C-a に変更
set -g prefix C-a
# デフォルトの C-b バインドを解除
unbind C-b
# C-a の重複押しで C-a を送信
bind C-a send-prefix

# マウス操作の有効化
set-option -g mouse on

# 256色ターミナルを有効化
set -g default-terminal "tmux-256color"

# ----------------------------------------------------
# 2. ステータスライン
# ----------------------------------------------------

# ステータスラインを上部に表示
set -g status-position top

# ----------------------------------------------------
# 3. キーバインド
# ----------------------------------------------------

# ペインの縦分割 (prefix + |)
bind | split-window -h
# ペインの横分割 (prefix + -)
bind - split-window -v

# ペイン移動 (prefix + hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# ----------------------------------------------------
# 4. プラグイン 
# ----------------------------------------------------

# @see https://github.com/catppuccin/tmux/discussions/317#discussioncomment-10890888
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d.%m. %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

# Load catppuccin
run $DOTFILES_DIR/catppuccin/tmux/catppuccin.tmux 

# set left and right status bar
set -g allow-rename off
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 0
set -g status-left '#{E:@catppuccin_status_session} '
set -g status-right ""

