# ----------------------------------------------------
# 1. 基本設定
# ----------------------------------------------------

# プレフィックスキーを C-a に変更
set -g prefix C-a
# デフォルトの C-b バインドを解除
unbind C-b
# C-a の重複押しで C-a を送信
bind C-a send-prefix
 
# マウス操作の有効化
set-option -g mouse on
 
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# ----------------------------------------------------
# 2. キーバインド
# ----------------------------------------------------

# ペインの縦分割 (prefix + |)
bind | split-window -h
# ペインの横分割 (prefix + -)
bind - split-window -v

# ペイン移動 (prefix + hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# カスタムスクリプト
bind-key -n C-Space run-shell "$DOTFILES_DIR/bin/tmux-switcher.sh"

# ----------------------------------------------------
# 4. UI
# ----------------------------------------------------

# @see https://github.com/catppuccin/tmux/discussions/317#discussioncomment-11064512

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

set -g status-interval 1

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_green}]  #S "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none] "
set -ga status-left "#[bg=#{@thm_yellow},fg=#{@thm_bg},bold]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=default,fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "
	
# Load catppuccin
run $DOTFILES_DIR/submodules/catppuccin/tmux/catppuccin.tmux

# Configure Tmux
set -g status-position top
set -g status-justify "absolute-centre"

# pane border look and feel
setw -g pane-border-status top
set -g pane-border-format "#[bg=default,fg=#{@thm_flamingo}]#(cat /tmp/tmux_last_command#{pane_tty} 2>/dev/null | grep -v '^exit$')"
# ↓ refresh 前に一瞬 exit の文字がでるので、上記で grep -v することで対処。ctrl + x で pane を閉じるケースには対応できないが、普段使わないので一旦許容。
# set-hook -g after-split-window { run-shell "echo '' |> '/tmp/tmux_last_command#{pane_tty}'" }
setw -g pane-active-border-style "fg=#{@thm_overlay_2}"
setw -g pane-border-style "fg=#{@thm_surface_0}"
setw -g pane-border-lines single

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "tmp"

set -g window-status-format ""
set -g window-status-current-format "#{?client_prefix,#{#[bg=#{@thm_peach},fg=#{@thm_bg},bold] #W },#{#[bg=#{@thm_bg},fg=#{@thm_peach},bold] #W }}"

# popup
set -g popup-border-style "fg=#{@thm_overlay_0}"

