# ----------------------------------------------------
# 1. 基本設定
# ----------------------------------------------------

# プレフィックスキーを C-a に変更
set -g prefix C-a
# デフォルトの C-b バインドを解除
unbind C-b
# C-a の重複押しで C-a を送信
bind C-a send-prefix

# マウス操作の有効化
set-option -g mouse on

# 256色ターミナルを有効化
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run $DOTFILES_DIR/catppuccin/tmux/catppuccin.tmux 

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# ----------------------------------------------------
# 2. ステータスライン
# ----------------------------------------------------

# ステータスラインを上部に表示
set -g status-position top

# ----------------------------------------------------
# 3. キーバインド
# ----------------------------------------------------

# ペインの縦分割 (prefix + |)
bind | split-window -h
# ペインの横分割 (prefix + -)
bind - split-window -v

# ペイン移動 (prefix + hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

