alias :q='exit'
alias cat='bat --paging=never'
alias dlf='docker logs -f --tail=100'
alias eza='LS_COLORS="" eza'
alias gad='git add'
alias gbr='git br'
alias gcm='git commit'
alias gcma='git commit --amend'
alias gco='git co'
alias gcob='git cob'
alias gdi-u='git -c delta.side-by-side=false diff'
alias gdi='git diff'
alias gdis-u='git -c delta.side-by-side=false diff --staged'
alias gdis='git diff --staged'
alias gf='git fetch'
alias gpu='git push origin HEAD'
alias gr='git restore'
alias grs='git restore --staged'
alias gst='git status -bs'
alias ls='eza -F --icons=auto'
alias m='make'
alias nv='nvim'
alias tree='ls -T'
